USE websafe  
CREATE TABLE  sw_holes_type(  /*漏洞类型表*/
   id int  NOT NULL  primary key identity(1,1),
   hole_type  text not null default '',
)
insert into sw_holes_type(hole_type) values
('缓冲区溢出'),
('SQL注入'),
('路径遍历'),
('跨站脚本'),
('资源管理错误'),
('权限许可和访问控制'),
('跨站请求伪造'),
('数字错误'),
('授权问题'),
('信任管理'),
('配置错误'),
('设计错误'),
('输入验证'),
('信息泄露'),
('代码注入'),
('加密问题'),
('竞争条件'),
('格式化字符串'),
('操作系统命令注入'),
('后置链接'),
('环境条件错误'),
('边界条件错误'),
('访问验证错误'),
('资料不足'),
('未知'),
('其他')